config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  scope format: false do # rubocop:disable Metrics/BlockLength
    constraints host: Rails.configuration.x.default_domain do # rubocop:disable Metrics/BlockLength
      use_doorkeeper do
        skip_controllers :applications, :authorized_applications
      end

      devise_for :users, only: :sessions, path: 'dashboard', path_names: { sign_in: 'login', sign_out: 'logout' }
      devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'dashboard/omniauth_callbacks' }
      devise_scope :user do
        unless ENV['REGISTRATION_DISABLED']
          get '/register', to: 'devise/registrations#new', as: :new_user_registration, format: false
          post '/register', to: 'devise/registrations#create', as: :user_registration, format: false
        end

        resource :confirmation, only: %i[new create show], path_names: { new: 'resend' },
                                path: '/dashboard/user/verify-email', controller: 'devise/confirmations',
                                as: :user_confirmation

        resource :password, only: %I[new create edit update], path_names: { new: 'recover', edit: 'reset' },
                            path: '/dashboard/user/password', controller: 'devise/passwords', as: :user_password

        resource :unlock, only: %i[new create show], path_names: { new: 'resend' },
                          path: '/dashboard/user/unlock', controller: 'devise/unlocks', as: :user_unlock
      end

      namespace :api do
        resource :user, only: %i[show]
        resources :links, only: %i[index create show update destroy]
        resources :domains, only: %i[index create show update destroy]

        root to: 'root#index'
      end

      namespace :dashboard, path: '/dashboard' do
        resource :account_profile, path: 'user', only: %i[show update destroy]

        resources :account_authorized_applications, path: 'user/applications/authorized', only: %i[index show destroy] do # rubocop:disable Layout/LineLength
          delete :revoke_all, path: 'revoke-all', on: :collection
        end
        resources :account_developer_applications, path: 'users/applications/developer' do
          delete :revoke, on: :member
          delete :secret, on: :member
        end
        resource :account_notifications, path: 'user/notifications', only: %i[show update]
        resource :account_security, path: 'user/security', controller: :account_security, only: %i[show update]

        resources :domains
        resources :links

        root to: 'home#index'
      end
    end
  end

  root to: 'home#index'

  resources :links, path: '', only: %i[show]
end

app/models/link.rb
# frozen_string_literal: true

# A link that can be redirected to.
#
# ## Schema Information
#
# Table name: `links`
#
# ### Columns
#
# Name               | Type               | Attributes
# ------------------ | ------------------ | ---------------------------
# **`id`**           | `uuid`             | `not null, primary key`
# **`archived_at`**  | `datetime`         |
# **`expires_in`**   | `integer`          |
# **`name`**         | `text`             | `not null`
# **`notes`**        | `text`             |
# **`properties`**   | `jsonb`            | `not null`
# **`tags`**         | `text`             | `default([]), not null, is an Array`
# **`target`**       | `text`             | `not null`
# **`title`**        | `text`             |
# **`created_at`**   | `datetime`         | `not null`
# **`updated_at`**   | `datetime`         | `not null`
# **`domain_id`**    | `uuid`             |
# **`owner_id`**     | `uuid`             | `not null`
#
# ### Indexes
#
# * `index_links_on_archived_at`:
#     * **`archived_at`**
# * `index_links_on_domain_id`:
#     * **`domain_id`**
# * `index_links_on_name_and_domain_id` (_unique_):
#     * **`name`**
#     * **`domain_id`**
# * `index_links_on_owner_id`:
#     * **`owner_id`**
# * `index_links_on_properties` (_using_ gin):
#     * **`properties`**
# * `index_links_on_tags` (_using_ gin):
#     * **`tags`**
# * `index_links_on_target`:
#     * **`target`**
#
# ### Foreign Keys
#
# * `fk_rails_...`:
#     * **`domain_id => domains.id`**
# * `fk_rails_...`:
#     * **`owner_id => users.id`**
#
class Link < ApplicationRecord
  belongs_to :owner, class_name: 'User', inverse_of: :links

  belongs_to :domain, inverse_of: :links, optional: true

  validates :target, url: true

  validates :name, uniqueness: { case_sensitive: true, scope: :domain_id }

  validate :domain_belongs_to_owner

  before_validation :generate_name, on: :create

  scope :on_default_domain, -> { where(domain_id: nil) }

  def tag_names
    tags.join(', ')
  end

  def tag_names=(val)
    self.tags = val.strip.gsub(/\s+/, ' ').split(',').map(&:strip)
  end

  private

  def generate_name
    self.name = ShortNameGenerator.new.call if name.blank?
  end

  def domain_belongs_to_owner
    return if domain.blank?

    errors.add(:domain, :must_belong_to_owner) unless domain.owner_id == owner_id
  end
end

app/controllers/dashboard/account_authorized_applications_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account authorized application settings controller.
  class AccountAuthorizedApplicationsController < DashboardController
    layout 'dashboard/accounts'

    before_action :find_application, only: %i[show destroy]

    def index
      @applications = Doorkeeper::Application.authorized_for(current_user)
    end

    def show
      @scopes = Doorkeeper::AccessToken.active_for(current_user)
                                       .where(application_id: @application.id)
                                       .map(&:scopes).map(&:to_a).flatten.uniq
    end

    def destroy
      Doorkeeper::AccessToken.revoke_all_for(@application.id, current_user)
      redirect_to dashboard_account_authorized_applications_path
    end

    def revoke_all
      Doorkeeper::AccessToken.active_for(current_user).map(&:revoke)
      redirect_to dashboard_account_authorized_applications_path
    end

    private

    def find_application
      @application = Doorkeeper::Application.authorized_for(current_user).find(params[:id])
    end
  end
end

app/controllers/dashboard/account_developer_applications_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account developer applications controller.
  class AccountDeveloperApplicationsController < DashboardController
    layout 'dashboard/accounts'

    before_action :find_application, only: %i[show update revoke secret destroy]

    def index
      @applications = current_user.developer_applications.order(:name)
    end

    def new
      @application = Doorkeeper::Application.new
    end

    def create
      @application = current_user.developer_applications.build(application_params)
      if @application.save
        redirect_to dashboard_account_developer_application_path(@application)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def update
      if @application.update(application_params)
        redirect_to dashboard_account_developer_application_path(@application)
      else
        render :show, status: :unprocessable_entity
      end
    end

    def revoke
      Doorkeeper::AccessToken.where(application_id: @application.id).each(&:revoke)
      redirect_to dashboard_account_developer_application_path(@application)
    end

    def secret
      @application.renew_secret
      @application.save
      redirect_to dashboard_account_developer_application_path(@application)
    end

    def destroy
      @application.destroy
      redirect_to dashboard_account_developer_applications_path
    end

    private

    def application_params
      params.require(:doorkeeper_application).permit(:name, :redirect_uri)
    end

    def find_application
      @application = current_user.developer_applications.find(params[:id])
    end
  end
end

app/controllers/dashboard/account_notifications_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account notification settings controller.
  class AccountNotificationsController < DashboardController
    layout 'dashboard/accounts'
  end
end

app/controllers/dashboard/account_profiles_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account profile settings controller.
  class AccountProfilesController < DashboardController
    layout 'dashboard/accounts'

    def update
      if current_user.update(profile_params)
        redirect_to dashboard_account_profile_path, notice: resource_notification_updated
      else
        render :show, status: :unprocessable_entity
      end
    end

    private

    def resource
      current_user
    end

    def resource_notification_updated_key
      'notifications.profile.updated'
    end

    def resource_errors_key
      'notifications.profile.errors'
    end

    def profile_params
      params.require(:user).permit(:email, :name)
    end
  end
end

app/controllers/dashboard/account_security_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account security settings controller.
  class AccountSecurityController < DashboardController
    layout 'dashboard/accounts'

    def update
      if resource.update_with_password(password_params)
        redirect_to dashboard_account_security_path, notice: resource_notification_updated
      else
        render :show, status: :unprocessable_entity
      end
    end

    private

    def resource
      current_user
    end

    def resource_notification_updated_key
      'dashboard.accounts.notifications.password.updated'
    end

    def password_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end
  end
end

app/controllers/dashboard/accounts_controller.rb
# frozen_string_literal: true

module Dashboard
  # Account profile settings controller.
  class AccountsController < DashboardController
    def update
      if current_user.update(profile_params)
        redirect_to dashboard_account_path, notice: resource_notification_updated
      else
        render :show, status: :unprocessable_entity
      end
    end

    private

    def resource
      current_user
    end

    def resource_notification_updated_key
      'notifications.profile.updated'
    end

    def resource_errors_key
      'notifications.profile.errors'
    end

    def profile_params
      params.require(:user).permit(:email, :name)
    end
  end
end

app/controllers/dashboard/domains_controller.rb
# frozen_string_literal: true

module Dashboard
  # Manages domains.
  class DomainsController < DashboardController
    before_action :find_domain, only: %i[show edit update destroy]

    def index
      @domains = current_user.domains.order(created_at: :desc).page(params[:page])
    end

    def new
      @domain = Domain.new
    end

    def create
      @domain = current_user.domains.build(domain_params)
      if @domain.save
        redirect_to dashboard_domain_path(@domain), notice: resource_notification_created
      else
        @domain.name = nil
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @domain.update(domain_params)
        redirect_to dashboard_domain_path(@domain), notice: resource_notification_updated
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @domain.destroy
      redirect_to dashboard_domains_path, notice: resource_notification_destroyed
    end

    private

    def domain_params
      params = ActionController::Parameters.new(request.request_parameters)
      params.require(:domain).permit(:name)
    end

    def find_domain
      @domain = current_user.domains.find(params[:id])
    end

    def resource
      @domain
    end
  end
end

app/controllers/dashboard/home_controller.rb
# frozen_string_literal: true

module Dashboard
  # Dashboard homepage controller.
  class HomeController < DashboardController
    layout 'home'
  end
end

app/controllers/dashboard/links_controller.rb
# frozen_string_literal: true

module Dashboard
  # Dashboard controller to manage links.
  class LinksController < DashboardController
    before_action :find_link, only: %i[show edit update destroy]

    def index
      @links = current_user.links.order(created_at: :desc).page(params[:page])
    end

    def new
      @link = Link.new
    end

    def create
      @link = current_user.links.build(link_params)
      if @link.save
        redirect_to dashboard_link_path(@link), notice: resource_notification_created
      else
        @link.name = nil
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @link.update(link_params)
        redirect_to dashboard_link_path(@link), notice: resource_notification_updated
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @link.destroy
      redirect_to dashboard_links_path, notice: resource_notification_destroyed
    end

    private

    def link_params
      params.require(:link).permit(:name, :target, :expires_in, :tag_names, :notes, :domain_id)
    end

    def find_link
      @link = current_user.links.find(params[:id])
    end

    def resource
      @link
    end
  end
end

app/controllers/dashboard/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Dashboard
  # Callbacks for 3rd party authentication.
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    prepend_before_action { request.env['devise.skip_timeout'] = true }

    def indieauth
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.present?
        sign_in_and_redirect @user, event: :authentication
        flash[:notice] = "Logged in successfully with IndieAuth from #{@user.indieauth_profile_url}"
      else
        flash[:notice] = 'You must register first before connecting to IndieAuth'
        redirect_to root_path
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Base class for dashboard controllers
class DashboardController < ApplicationController
  include ResourceNotifications

  before_action :authenticate_user!
end

app/controllers/links_controller.rb
# frozen_string_literal: true

# Controller to manage links and redirects them to their targets.
class LinksController < ApplicationController
  layout 'home'

  def show
    @link = default_domain? ? find_link_on_default_domain : find_link_on_domain
    redirect_or_not_found(@link)
  end

  private

  def find_link_on_default_domain
    Link.on_default_domain.find_by(name: params[:id])
  end

  def find_link_on_domain
    domain = Domain.find_by(name: request.domain)
    domain&.links&.find_by(name: params[:id]) if domain.present?
  end

  def redirect_or_not_found(link)
    if link.present?
      redirect_to URI.parse(link.target).to_s, status: :moved_permanently
    else
      render_not_found
    end
  end

  def render_not_found
    render :not_found, status: :not_found
  end

  def default_domain?
    request.host == Rails.configuration.x.default_domain
  end
end

app/helpers/dashboard/account_authorized_applications_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for account authorized applications views.
  module AccountAuthorizedApplicationsHelper
  end
end

app/helpers/dashboard/account_developer_applications_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for account developer applications views.
  module AccountDeveloperApplicationsHelper
    def developer_application_active_users_count(application)
      @developer_application_active_users_count ||= application.access_tokens
                                                               .where(revoked_at: nil)
                                                               .distinct.count(:resource_owner_id)
    end
  end
end

app/helpers/dashboard/account_notifications_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for account notifications views.
  module AccountNotificationsHelper
  end
end

app/helpers/dashboard/account_profiles_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for account profile views.
  module AccountProfilesHelper
  end
end

app/helpers/dashboard/account_security_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for account security views.
  module AccountSecurityHelper
  end
end

app/helpers/dashboard/domains_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for dashboard domain views.
  module DomainsHelper
  end
end

app/helpers/dashboard/home_helper.rb
# frozen_string_literal: true

module Dashboard
  # Helpers for the dashboard homepage.
  module HomeHelper
  end
end

app/views/dashboard/links/_link_fields.html.erb
<% unless @link.persisted? %>
  <div class="field">
    <%= f.label :domain_id, t('.domain_id.label'), class: 'label' %>
    <div class="control">
      <div class="select">
        <%= f.select :domain_id, current_user.domains.order(:name).map { |d| [d.name, d.id] }, include_blank: Rails.configuration.x.default_domain %>
      </div>
    </div>
  </div>
<% end %>

<div class="field">
  <%= f.label :name, t('.name.label', link: link_url('NAME')), class: 'label' %>
  <div class="control"><%= f.text_field :name, class: 'input', placeholder: t('.name.placeholder') %></div>
</div>

<div class="field">
  <%= f.label :target, t('.target.label'), class: 'label' %>
  <div class="control"><%= f.text_field :target, class: 'input', placeholder: t('.target.placeholder') %></div>
</div>

<div class="field">
  <%= f.label :expires_in, t('.expires_in.label'), class: 'label' %>
  <div class="control"><%= f.text_field :expires_in, class: 'input', placeholder: t('.expires_in.placeholder') %></div>
</div>

<div class="field">
  <%= f.label :tag_names, t('.tag_names.label'), class: 'label' %>
  <div class="control"><%= f.text_field :tag_names, class: 'input', placeholder: t('.tag_names.placeholder') %></div>
</div>

app/views/dashboard/links/edit.html.erb
<main id="main" aria-role="main">
  <section class="section">
    <div class="container pb-6">
      <%= render 'notifications' %>
      <div class="columns is-centered">
        <div class="column is-three-fifths">
          <div class="card">
            <div class="card-content">
              <div class="container has-text-centered pb-4">
                <h1 class="title has-text-dark"><% t('.title') %></h1>
              </div>

              <%= render 'form_errors' %>

              <%= form_for(@link, url: dashboard_link_path(@link)) do |f| %>
                <%= render partial: 'link_fields', locals: { f: f } %>

                <%= f.submit t('.submit'), class: 'button is-primary is-large is-fullwidth' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/dashboard/links/index.html.erb
<% if @links.any? %>
<div class="level">
  <div class="level-left">
    <h1 class="title has-text-centered"><%= t '.title' %></h1>
  </div>
  <div class="level-right">
    <%= link_to t('.new'), new_dashboard_link_path, class: 'button is-primary is-medium' %>
  </div>
</div>
<%= render 'notifications' %>
<table class="table is-bordered is-striped is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th><%= t '.table.headers.name' %></th>
      <th><%= t '.table.headers.tags' %></th>
      <th><%= t '.table.headers.created_at' %></th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td>
          <h3><%= link_to link_url(link.name, domain: link.domain&.name), dashboard_link_path(link), class: 'has-text-dark is-size-4' %></h3>
          <h4><%= link.target %></h4>
        </td>
        <td>
          <% if link.tags.any? %>
            <div class="tags">
              <% link.tags.each do |t| %><span class="tag"><%= t %></span><% end %>
            </div>
          <% end %>
        </td>
        <td><%= local_time link.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= paginate @links %>
      </td>
    </tr>
  </tfoot>
</table>
<% else %>
<% end %>

app/views/dashboard/links/new.html.erb
<main id="main" aria-role="main">
  <section class="section">
    <div class="container pb-6">
      <%= render 'notifications' %>
      <div class="columns is-centered">
        <div class="column is-three-fifths">
          <div class="card">
            <div class="card-content">
              <div class="container has-text-centered pb-4">
                <h1 class="title has-text-dark"><% t('.title') %></h1>
              </div>

              <%= render 'form_errors' %>

              <%= form_for(@link, url: dashboard_links_path) do |f| %>
                <%= render partial: 'link_fields', locals: { f: f } %>

                <%= f.submit t('.submit'), class: 'button is-primary is-large is-fullwidth' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/dashboard/links/show.html.erb
<main id="main" aria-role="main">
  <section class="section">
    <div class="container pb-6">
      <%= render 'notifications' %>
      <div class="columns is-centered">
        <div class="column is-three-fifths">
          <div class="card">
            <header class="card-header">
              <h1 class="card-header-title"><%= link_url(@link.name, domain: @link.domain&.name) %></h1>
              <div class="card-header-icon">
                <span class="icon">
                  <%= link_to link_url(@link.name, domain: @link.domain&.name), class: 'has-text-dark' do %><i class="fas fa-external-link-alt"></i><% end %>
                </span>
                <span class="icon ml-3">
                  <%= link_to edit_dashboard_link_path(@link), class: 'has-text-dark' do %><i class="fas fa-edit"></i><% end %>
                </span>
                <span class="icon ml-3">
                  <%= link_to dashboard_link_url(@link), method: :delete, data: { confirm: 'Are you sure?' }, class: 'has-text-dark' do %><i class="fas fa-trash"></i><% end %>
                </span>
              </div>
            </header>
            <div class="card-content">
              <p>
                <i class="fas fa-link has-text-dark"></i>
                &nbsp;
                <%= link_to @link.target, URI.parse(@link.target).to_s, target: '_blank', class: 'has-text-dark' %>
              </p>

              <div class="level mt-3">
                <div class="level-left">
                  <div class="level-item">
                    <small>
                      <i class="fas fa-calendar"></i>
                      &nbsp;
                      <%= local_time @link.created_at %>
                    </small>
                  </div>
                </div>
                <div class="level-right">
                  <div class="level-item">
                    <% if @link.tags.any? %>
                      <div class="tags">
                        <% @link.tags.each do |t| %><span class="tag"><%= t %></span><% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>